#ifndef _VBLK_HW_OPS_H
#define _VBLK_HW_OPS_H

#include <linux/types.h>
#include <linux/io.h>
#include <linux/dma-mapping.h>
#include <linux/pci.h>
#include <linux/mm.h>

/*
 * Hardware abstraction layer.
 * These functions wrap low-level MMIO, DMA, and memory barrier operations.
 * They are called by LLM-generated code but NOT generated by SYSSPEC.
 *
 * MMIO register offsets follow the virtio-mmio v2 specification.
 * For PCI transport, the virtio-mmio capability is mapped from BAR0.
 */
#define VIO_REG_MAGIC           0x000
#define VIO_REG_VERSION         0x004
#define VIO_REG_DEVICE_ID       0x008
#define VIO_REG_VENDOR_ID       0x00c
#define VIO_REG_DEVICE_FEAT     0x010
#define VIO_REG_DEVICE_FEAT_SEL 0x014
#define VIO_REG_DRIVER_FEAT     0x020
#define VIO_REG_DRIVER_FEAT_SEL 0x024
#define VIO_REG_QUEUE_SEL       0x030
#define VIO_REG_QUEUE_NUM_MAX   0x034
#define VIO_REG_QUEUE_NUM       0x038
#define VIO_REG_QUEUE_READY     0x044
#define VIO_REG_QUEUE_NOTIFY    0x050
#define VIO_REG_INT_STATUS      0x060
#define VIO_REG_INT_ACK         0x064
#define VIO_REG_STATUS          0x070
#define VIO_REG_CONFIG          0x100  /* Device-specific config space */

/* ---- Memory barriers ---- */
static inline void hw_mb(void)
{
	mb();
}

static inline void hw_rmb(void)
{
	rmb();
}

static inline void hw_wmb(void)
{
	wmb();
}

/* ---- DMA memory allocation ---- */
/* Returns virtual address, sets *dma_handle to DMA address. NULL on failure. */
static inline void *hw_dma_alloc_coherent(struct device *dev, size_t size,
					  dma_addr_t *dma_handle)
{
	return dma_alloc_coherent(dev, size, dma_handle, GFP_KERNEL);
}

static inline void hw_dma_free_coherent(struct device *dev, size_t size,
					void *vaddr, dma_addr_t dma_handle)
{
	dma_free_coherent(dev, size, vaddr, dma_handle);
}

/* ---- PCI BAR mapping ---- */
/* Maps a PCI BAR and returns the virtual address. NULL on failure. */
static inline void __iomem *hw_pci_iomap(struct pci_dev *pdev, int bar,
					  resource_size_t maxlen)
{
	resource_size_t len = pci_resource_len(pdev, bar);
	if (maxlen && len > maxlen)
		len = maxlen;
	if (pci_request_region(pdev, bar, "virtio-blk"))
		return NULL;
	return ioremap(pci_resource_start(pdev, bar), len);
}

static inline void hw_pci_iounmap(void __iomem *addr)
{
	iounmap(addr);
}

/* ---- Device status management ---- */
static inline u8 hw_get_device_status(void __iomem *ioaddr)
{
	return ioread8(ioaddr + VIO_REG_STATUS);
}

static inline void hw_set_device_status(void __iomem *ioaddr, u8 status)
{
	iowrite8(status, ioaddr + VIO_REG_STATUS);
}

/* ---- PCI capability access ---- */
/* Read a 32-bit value from the vendor-specific capability at offset. */
static inline u32 hw_pci_cfg_read32(struct pci_dev *pdev, int pos)
{
	u32 val;
	pci_read_config_dword(pdev, pos, &val);
	return val;
}

/* ---- Notification (doorbell) ---- */
static inline void hw_notify(void __iomem *ioaddr, u16 queue_index, u16 off)
{
	/* Modern: write queue index to notification bar */
	iowrite16(queue_index, ioaddr + off);
}

/* ---- Kernel memory allocation ---- */
static inline void *hw_kmalloc(size_t size)
{
	return kmalloc(size, GFP_KERNEL);
}

static inline void *hw_kzalloc(size_t size)
{
	return kzalloc(size, GFP_KERNEL);
}

static inline void hw_kfree(void *ptr)
{
	kfree(ptr);
}

/* ---- Interrupt enable/disable on device ---- */
static inline void hw_vq_enable_interrupt(void __iomem *ioaddr,
					   u16 queue_index, u16 off)
{
	/* Write 0 to queue interrupt suppression (enable) */
	iowrite16(0, ioaddr + off + queue_index * 4 + 2);
}

static inline void hw_vq_disable_interrupt(void __iomem *ioaddr,
					    u16 queue_index, u16 off)
{
	/* Write 1 to queue interrupt suppression (disable) */
	iowrite16(1, ioaddr + off + queue_index * 4 + 2);
}

/* ---- MMIO helpers for virtio_blk_dev ---- */
#define vblk_ioread8(vdev, off)   ioread8((vdev)->ioaddr + (off))
#define vblk_ioread16(vdev, off)  ioread16((vdev)->ioaddr + (off))
#define vblk_ioread32(vdev, off)  ioread32((vdev)->ioaddr + (off))
#define vblk_iowrite8(vdev, off, val)   iowrite8((val), (vdev)->ioaddr + (off))
#define vblk_iowrite16(vdev, off, val)  iowrite16((val), (vdev)->ioaddr + (off))
#define vblk_iowrite32(vdev, off, val)  iowrite32((val), (vdev)->ioaddr + (off))

#endif /* _VBLK_HW_OPS_H */
