/*
 * virtio-blk driver skeleton (virtio PCI driver).
 * Uses kernel virtio API for device probing and virtqueue setup.
 *
 * Hand-written boilerplate: PCI probe/remove, feature table.
 * Generated code: blkdev_init, blkdev_exit (block device registration),
 *   blk_submit, blk_done (I/O path).
 *
 * Note: The dev_reset/dev_negotiate/dev_read_config/dev_setup_vqs functions
 * in virtio-core/ use MMIO register access for virtio-mmio transport.
 * For virtio-pci transport (used here), the kernel virtio API handles
 * device status, feature negotiation, and config space internally.
 */
#include "common.h"
#include "driver/driver.h"
#include "virtio-blk/virtio_blk.h"

static int vblk_probe(struct virtio_device *vdev)
{
	struct virtio_blk_dev *vbdev;
	struct virtqueue *vqs[1];
	struct virtqueue_info vq_info[1];
	int ret;

	pr_info("virtio-blk-sysspec: probe called for %s\n",
		dev_name(&vdev->dev));

	vbdev = kzalloc(sizeof(*vbdev), GFP_KERNEL);
	if (!vbdev)
		return -ENOMEM;

	vbdev->vdev = vdev;
	vdev->priv = vbdev;

	if (vdev->dev.parent && dev_is_pci(vdev->dev.parent))
		vbdev->pdev = to_pci_dev(vdev->dev.parent);

	/*
	 * Use virtio kernel API for feature negotiation and config.
	 * The kernel handles transport-specific details (PCI config space,
	 * MMIO capabilities) transparently.
	 */
	vbdev->features = vdev->config->get_features(vdev);

	/* Read device config via virtio API */
	vdev->config->get(vdev, offsetof(struct virtio_blk_config, capacity),
			  &vbdev->config.capacity, sizeof(vbdev->config.capacity));
	vbdev->config.capacity = le64_to_cpu(vbdev->config.capacity);
	vbdev->config.blk_size = 512; /* Default; override if feature negotiated */
	vdev->config->get(vdev, offsetof(struct virtio_blk_config, blk_size),
			  &vbdev->config.blk_size, sizeof(vbdev->config.blk_size));
	vbdev->config.blk_size = le32_to_cpu(vbdev->config.blk_size);
	if (!vbdev->config.blk_size)
		vbdev->config.blk_size = 512;

	vbdev->num_queues = 1;

	/* Set up virtqueues using kernel API with completion callback */
	vq_info[0].name = "virtio-blk.0";
	vq_info[0].callback = blk_done;
	vq_info[0].ctx = false;

	ret = virtio_find_vqs(vdev, 1, vqs, vq_info, NULL);
	if (ret) {
		pr_err("virtio-blk-sysspec: failed to find vqs: %d\n", ret);
		goto err_free;
	}

	vbdev->vq = vqs[0];
	vbdev->queue_size = virtqueue_get_vring_size(vbdev->vq);

	/* Set DRIVER_OK before device_add_disk triggers partition scan I/O.
	 * The virtio core sets DRIVER_OK after probe returns, but we need
	 * the device to process I/O during probe (device_add_disk).
	 */
	virtio_device_ready(vdev);

	/* Register as block device (uses generated code) */
	ret = blkdev_init(vbdev);
	if (ret) {
		pr_err("virtio-blk-sysspec: block device init failed: %d\n", ret);
		goto err_del_vqs;
	}

	pr_info("virtio-blk-sysspec: device ready: %llu sectors, %u byte sectors, "
		"queue_size=%u, features=0x%llx\n",
		(u64)vbdev->config.capacity, vbdev->config.blk_size,
		vbdev->queue_size, vbdev->features);

	return 0;

err_del_vqs:
	vdev->config->del_vqs(vdev);
err_free:
	kfree(vbdev);
	return ret;
}

static void vblk_remove(struct virtio_device *vdev)
{
	struct virtio_blk_dev *vbdev = vdev->priv;

	pr_info("virtio-blk-sysspec: removing device %s\n",
		dev_name(&vdev->dev));
	blkdev_exit(vbdev);
	vdev->config->del_vqs(vdev);
	kfree(vbdev);
}

static const struct virtio_device_id vblk_id_table[] = {
	{ VIRTIO_ID_BLOCK, VIRTIO_DEV_ANY_ID },
	{ 0 },
};

static unsigned int features[] = {
	VIRTIO_BLK_F_SIZE_MAX,
	VIRTIO_BLK_F_SEG_MAX,
	VIRTIO_BLK_F_GEOMETRY,
	VIRTIO_BLK_F_RO,
	VIRTIO_BLK_F_BLK_SIZE,
	VIRTIO_BLK_F_FLUSH,
	VIRTIO_BLK_F_TOPOLOGY,
	VIRTIO_BLK_F_CONFIG_WCE,
};

static struct virtio_driver vblk_virtio_driver = {
	.driver.name = "virtio-blk-sysspec",
	.driver.owner = THIS_MODULE,
	.id_table = vblk_id_table,
	.feature_table = features,
	.feature_table_size = ARRAY_SIZE(features),
	.probe = vblk_probe,
	.remove = vblk_remove,
};

static int __init vblk_init(void)
{
	pr_info("virtio-blk-sysspec: loading\n");
	return register_virtio_driver(&vblk_virtio_driver);
}

static void __exit vblk_exit(void)
{
	pr_info("virtio-blk-sysspec: unloading\n");
	unregister_virtio_driver(&vblk_virtio_driver);
}

module_init(vblk_init);
module_exit(vblk_exit);

MODULE_LICENSE("GPL");
MODULE_AUTHOR("SYSSPEC Generated");
MODULE_DESCRIPTION("Virtio-blk driver generated by SYSSPEC");
