#ifndef _UART16550_HW_OPS_H
#define _UART16550_HW_OPS_H

#include <linux/types.h>
#include <asm/io.h>

/*
 * Hardware abstraction for 8250/16550 port I/O.
 * Hand-written: not generated by SYSSPEC.
 */
static inline unsigned int hw_inb(unsigned long port)
{
	return inb(port);
}

static inline void hw_outb(unsigned long port, u8 val)
{
	outb(val, port);
}

#define UART16550_PORT_REG(base, reg) ((base) + (reg))

#endif /* _UART16550_HW_OPS_H */
